### ISSUE TITLE
Please kindly share this CSV File C:\Users\haq\OneDrive\Notebooks\data\AdvWorksData.csv 

### ISSUE THREAD

**Issue by jmbayu** [hnawaz007/pythondataanalysis#6]
Great Tutorial.

I am follwing the pyspark notebook step by step and got stuck here

df=spark.read.options(delimiter=",", header=True).csv(r"C:\Users\haq\OneDrive\Notebooks\data\AdvWorksData.csv")
df.show()

I currently have no microsoft excel at hand, when i tried to convert  AdvWorksData.xlsx to CSV with MacOS Numbers it gives me two incompatible CSV-Files. 

Thx in advance.

**Comment by hnawaz007** [comment]
Thanks! Here is the CSV file. [AdvWorksData.csv](https://github.com/hnawaz007/pythondataanalysis/files/10080289/AdvWorksData.csv)
